services:
  nginx:
    image: nginx:latest
    ports: 
      - "5086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlservice_blue
      - mlservice_green
      